=== mijnaansluiting/Inhoudelijke-validaties/doc/NLCSValidatieRegels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="NLCSValidatieRegelsNameSpace"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="NLCSValidatieRegelsNameSpace"
		   elementFormDefault="qualified"
		   attributeFormDefault="unqualified">

	<!--- Type Definities -->
	<xs:simpleType name="SoortValidatieRegelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bestand"/>
			<xs:enumeration value="Document"/>
			<xs:enumeration value="Geometrie"/>
			<xs:enumeration value="Verplichte waarde"/>
			<xs:enumeration value="Inhoud waarde"/>
			<xs:enumeration value="Topologie"/>
			<xs:enumeration value="Netlogica"/>
			<xs:enumeration value="Consistentie"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NiveauRegelType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fout"/>
			<xs:enumeration value="Waarschuwing"/>
			<xs:enumeration value="Informerend"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="NLCSObjectType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Document"/>
			<xs:enumeration value="AlleObjecten"/>
			<xs:enumeration value="AprojectReferentie"/>
			<xs:enumeration value="LSkast"/>
			<xs:enumeration value="LSmof"/>
			<xs:enumeration value="LSkabel"/>
			<xs:enumeration value="LSoverdrachtspunt"/>
			<xs:enumeration value="OVLoverdrachtspunt"/>
			<xs:enumeration value="MSstation"/>
			<xs:enumeration value="MSoverdrachtspunt"/>
			<xs:enumeration value="MSkabel"/>
			<xs:enumeration value="MSmof"/>
			<xs:enumeration value="Amantelbuis"/>
			<xs:enumeration value="AmantelbuisInhoud"/>
			<xs:enumeration value="Eaardmof"/>
			<xs:enumeration value="Eaarddraad"/>
			<xs:enumeration value="Eaardpen"/>
			<xs:enumeration value="HSkabel"/>
			<xs:enumeration value="HSmof"/>
			<xs:enumeration value="HSstation"/>
			<xs:enumeration value="Eoliedrukinstallatie"/>
			<xs:enumeration value="Eoliedrukleiding"/>
			<xs:enumeration value="Apmerking]"/>
			<xs:enumeration value="Amaaiveldhoogte"/>
			<xs:enumeration value="Abestand_bijlage"/>
			<xs:enumeration value="Akunstwerk"/>
			<xs:enumeration value="Aaanlegtechniek"/>
			<xs:enumeration value="AbeschermingVlak"/>
			<xs:enumeration value="Amarkeringsobject"/>
			<xs:enumeration value="AinUittredepunt"/>
			<xs:enumeration value="AbeschermingVlak"/>
			<xs:enumeration value="Gstation"/>
			<xs:enumeration value="Gleiding"/>
			<xs:enumeration value="Gafsluiter"/>
			<xs:enumeration value="GTstuk"/>
			<xs:enumeration value="Goverdrachtspunt"/>
			<xs:enumeration value="Gaftakzadel"/>
			<xs:enumeration value="Geindstuk"/>
			<xs:enumeration value="GappendageOverig"/>
			<xs:enumeration value="Gisolatiestuk"/>
			<xs:enumeration value="Govergangstuk"/>
			<xs:enumeration value="Gmeetpunt"/>
			<xs:enumeration value="Gleidingafblaas"/>
			<xs:enumeration value="Gsifon"/>
			<xs:enumeration value="GvertikaleBocht"/>
			<xs:enumeration value="Gontspanningselement"/>
			<xs:enumeration value="Gblaasgatzadel"/>
			<xs:enumeration value="KBgelijkrichter"/>
			<xs:enumeration value="KBmeetpaal"/>
			<xs:enumeration value="KBmeetdraad"/>
			<xs:enumeration value="KBanode"/>
			<xs:enumeration value="KBdrainage"/>
			<xs:enumeration value="KBobject"/>
			<xs:enumeration value="Tstation"/>
			<xs:enumeration value="Tbuis"/>
			<xs:enumeration value="Tkabel"/>
			<xs:enumeration value="Tmof"/>
			<xs:enumeration value="Toverdrachtspunt"/>

		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ObjectSoortType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LS"/>
			<xs:enumeration value="MS"/>
			<xs:enumeration value="HS"/>
			<xs:enumeration value="Station/Kast"/>
			<xs:enumeration value="Algemeen"/>
			<xs:enumeration value="Telecom"/>
			<xs:enumeration value="Gas"/>
			<xs:enumeration value="KB"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ValidatieObjectType">
		<xs:sequence>
			<xs:element name="naam"        type="NLCSObjectType"  minOccurs="1" maxOccurs="1"/>
			<!-- <xs:element name="soortObject" type="ObjectSoortType" minOccurs="1" maxOccurs="1"/>  -->
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ValidatieObjectVerzamelingType">
		<xs:sequence>
			<xs:element name="validatieObject" type="ValidatieObjectType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="TekeningSoortType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bestaande Situatie"/>
			<xs:enumeration value="Definitief Ontwerp"/>
			<xs:enumeration value="Deelrevisie"/>
			<xs:enumeration value="Eindrevisie"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StatusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BESTAAND"/>
			<xs:enumeration value="NIEUW"/>
			<xs:enumeration value="REVISIE"/>
			<xs:enumeration value="VERWIJDERD"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="StatusVerzamelingType">
		<xs:sequence>
			<xs:element name="status" type="StatusType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="BedrijfsToestandType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="IN BEDRIJF"/>
			<xs:enumeration value="RESERVE"/>
			<xs:enumeration value="VERLATEN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="BedrijfsToestandVerzamelingType">
		<xs:sequence>
			<xs:element name="bedrijfstoestand" type="BedrijfsToestandType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ScopeType">
		<xs:sequence>
			<xs:element name="tekeningSoort"      type="TekeningSoortType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="statussen"          type="StatusVerzamelingType" minOccurs="1" maxOccurs="1" />
			<xs:element name="bedrijfsToestanden" type="BedrijfsToestandVerzamelingType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="scopeValidatieRegels" type="ScopeValidatieRegelsVerzamelingType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="naam" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="ScopeVerzamelingType">
		<xs:sequence>
			<xs:element name="scope" type="ScopeType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ValidatieRegelType">
		<xs:sequence>
			<xs:element name="beschrijving"     type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Een korte beschrijving van de inhoudelijke validatie</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="soort"            type="SoortValidatieRegelType" minOccurs="1" maxOccurs="1"/>
			<xs:element name="definitie"        type="xs:string" minOccurs="1" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Definitie waarmee de daadwerkelijke Schematron inhoudelijke validatie ontwikkeld kan worden</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="toelichting"       type="xs:string" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>Ruimte voor aanvullend toelichting wat niet past in beschrijving of definitie</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="validatieObjecten" type="ValidatieObjectVerzamelingType" minOccurs="1" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="nummer" type="xs:ID" use="required"/>
		<xs:attribute name="naam" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="ValidatieRegelVerzamelingType">
		<xs:sequence>
			<xs:element name="validatieRegel" type="ValidatieRegelType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ScopeValidatieRegelsReferentieType">
		<xs:sequence>
			<xs:element name="nummer" type="xs:IDREF" minOccurs="1" maxOccurs="1"/>
			<xs:element name="niveau" type="NiveauRegelType" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ScopeValidatieRegelsVerzamelingType">
		<xs:sequence>
			<xs:element name="scopeValidatieRegel" type="ScopeValidatieRegelsReferentieType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<!--  Root element -->
	<xs:element name="NLCSValidatieregels">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="validatieRegels" type="ValidatieRegelVerzamelingType" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="scopes" type="ScopeVerzamelingType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mijnaansluiting/Inhoudelijke-validaties/doc/NLCSValidatieRegels.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type='text/xsl' href="NLCSValidatieRegels.xsl"?>
<NLCSValidatieregels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		     xsi:schemaLocation="NLCSValidatieRegelsNameSpace NLCSValidatieRegels.xsd"
		     xmlns="NLCSValidatieRegelsNameSpace">
	<validatieRegels>
		<validatieRegel nummer="R.1" naam="Bestand bevat NLCS Objecten">
			<beschrijving>Het NLCS++ bestand moet één of meerdere NLCS++ objecten bevatten</beschrijving>
			<soort>Bestand</soort>
			<definitie>
				Een NLCS++ bestand moet een AProjectReferentie hebben waarin tenminste 1 NLCS Object zit.
			</definitie>
			<toelichting>Er mag geen 'leeg' project ingeleverd worden, oftewel met alleen maar één Aprojectreferentie</toelichting>
			<validatieObjecten>
				<validatieObject><naam>Document</naam></validatieObject>
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.2" naam="Combinatie NLCS Status en Tekeningsoort">
			<beschrijving>Afhankelijk van het Tekeningsoort mogen er NLCS Objecten voorkomen met bepaalde NLCS Statussen</beschrijving>
			<soort>Bestand</soort>
			<definitie>
				Bestaande Situatie: BESTAAND
				Definitief Ontwerp: BESTAAND, NIEUW, REVISIE en VERWIJDERD
				Deelrevisie: BESTAAND, NIEUW, REVISIE en VERWIJDERD
				Eindrevisie: BESTAAND, NIEUW, REVISIE en VERWIJDERD
			</definitie>
			<validatieObjecten>
				<validatieObject><naam>Document</naam></validatieObject>
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.3" naam="Geometrie binnen Projectvlak">
			<beschrijving>Iedere geometrie (punt, lijn en vlak) van ieder NLCS Object in het bestand moet interactie hebben met het Projectgebied van AProjectReferentie</beschrijving>
			<soort>Geometrie</soort>
			<definitie>
				Het kenmerk Geometry (gml:Point, gml:Curve of gml:Surface) moet interactie hebben met de Geometry (gml:Surface) van de AprojectReferentie
			</definitie>
			<validatieObjecten>
		    	<validatieObject><naam>MSmof</naam></validatieObject>
		    	<validatieObject><naam>MSoverdrachtspunt</naam></validatieObject>
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>Amantelbuis</naam></validatieObject>
				<validatieObject><naam>Akunstwerk</naam></validatieObject>
				<validatieObject><naam>Eaarddraad</naam></validatieObject>
				<validatieObject><naam>Aaanlegtechniek</naam></validatieObject>
				<validatieObject><naam>MSstation</naam></validatieObject>
				<validatieObject><naam>AbeschermingVlak</naam></validatieObject>
		    </validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.4" naam="Lijn Geometrie">
			<beschrijving>Een lijn en de omtrek van vlak moeten voldoen aan inmeeteisen</beschrijving>
			<soort>Geometrie</soort>
			<definitie>
				Een gml:Curve moet voldoen aan de volgende inmeeteisen:
					- minimale (10cm) en maximale (50m) afstand van (inmeet)punten
					- mag geen knikken bevatten: hoek tussen segmenten > 45 graden.

				Een gml:Surface moet voldoen aan de volgende definitie:
					- minimale (10cm) en maximale (50m) afstand van (inmeet)punten
			</definitie>
			<validatieObjecten>
			     <!-- Deze regel geldt voor alle NLCS Objecten met een gml:Curve-->
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>Eaarddraad</naam></validatieObject>
				<validatieObject><naam>Aaanlegtechniek</naam></validatieObject>
				<validatieObject><naam>Amantelbuis</naam></validatieObject>
				<validatieObject><naam>MSstation</naam></validatieObject>

				<!--
				<validatieObject><naam>LSkabel</naam></validatieObject>
				<validatieObject><naam>HSkabel</naam></validatieObject>
				<validatieObject><naam>Gleiding</naam></validatieObject>
				<validatieObject><naam>KBmeetdraad</naam></validatieObject>
				<validatieObject><naam>Tkabel</naam></validatieObject>
				<validatieObject><naam>Tbuis</naam></validatieObject>
				<validatieObject><naam>Eoliedrukleiding</naam></validatieObject>
				<validatieObject><naam>Akunstwerk</naam></validatieObject>
				<validatieObject><naam>LSkast</naam></validatieObject>
				<validatieObject><naam>HSstation</naam></validatieObject>
				<validatieObject><naam>Gstation</naam></validatieObject>
				<validatieObject><naam>Tstation</naam></validatieObject>
				<validatieObject><naam>AbeschermingVlak</naam></validatieObject>
				 -->
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.5" naam="GisId en AssetId">
			<beschrijving>Ieder NLCS Object met de status BESTAAND, REVISIE en VERWIJDERD moet een GisId en AssetId hebben, dit zijn namelijk objecten die als oorsprong de assetregistratie hebben. NLCS objecten met de status NIEUW mogen juist geen GisId en AssetId hebben omdat deze objecten ontstaan in het ontwerp of de revisie.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				Als Status = BESTAAND, REVISIE* of VERWIJDERD, dan moet er een waarde zijn voor zowel kenmerk GisId als AssetId,
				Als Status = NIEUW dan moeten de kenmerken GisId en AssetId leeg zijn

				*Indien Status = REVISIE en Bewerking = VERPLAATSEN hoeft deze controle niet uitgevoerd te worden. Zie R.29 voor meer details.
			</definitie>
			<toelichting>Een AmantelbuisInhoud heeft nooit een GisId.</toelichting>
		    <validatieObjecten> <!-- Deze regel geldt voor alle NLCS Objecten -->
		    	<validatieObject><naam>AlleObjecten</naam></validatieObject>
		    </validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.6" naam="Inmeetwijze en Nauwkeurigheid Lineaire Assets Elec">
			<beschrijving>Ieder lineair NLCS Object voor Elec moet waardes hebben voor de kenmerken Inmeetwijze en Nauwkeurigheid.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				Ieder lineair NLCS Object voor Elec moet waardes hebben voor de kenmerken Inmeetwijze en Nauwkeurigheid.
			</definitie>
			<validatieObjecten>
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>Amantelbuis</naam></validatieObject>
				<!--
				<validatieObject><naam>LSkabel</naam></validatieObject>
				<validatieObject><naam>HSkabel</naam></validatieObject>
				 -->
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.7" naam="Subnettype gevuld voor LS en MS Kabel">
			<beschrijving>MSkabel, LSkabel en LSmof moeten een waarde hebben voor Subnettype.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				MSkabel, LSkabel en LSmof moeten een waarde hebben voor kenmerk Subnettype.
			</definitie>
			<validatieObjecten>
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>LSkabel</naam></validatieObject>
				<validatieObject><naam>LSmof</naam></validatieObject>
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.8" naam="Verplichte kenmerken Kabels">
			<beschrijving>Iedere kabel heeft kenmerken die gevuld moeten zijn.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				Iedere kabel moet een waarde voor de volgende kenmerken hebben:
					- Uitvoering
					- Kabelopbouw
					- Fabrikant
					- Verbindingnummer
					- Spanningsniveau
					- FaseAanduiding
					Voor LSkabel objecten zijn er nog 3 extra kenmerken die gevuld moeten zijn:
					- Aardingsysteem
					- Bovengronds
					- Functie
				N.B. Als het kenmerk Uitvoering de waarde "KEUZE ONTBREEKT IN LIJST" dan moet het kenmerk OmschrijvingUitvoering gevuld zijn!
			</definitie>
			<validatieObjecten>
				<validatieObject><naam>LSkabel</naam></validatieObject>
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>HSkabel</naam></validatieObject>
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.9" naam="Aanlegdatum gevuld">
			<beschrijving>De aanlegdatum moet gevuld zijn en mag niet in de toekomst liggen.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				De aanlegdatum moet gevuld zijn en de gevulde datum mag niet in de toekomst liggen.
			</definitie>
			<validatieObjecten> <!-- Deze regel geldt voor alle NLCS Objecten van Elec -->
				<validatieObject><naam>MSstation</naam></validatieObject>
				<validatieObject><naam>MSkabel</naam></validatieObject>
				<validatieObject><naam>MSmof</naam></validatieObject>
				<validatieObject><naam>MSoverdrachtspunt</naam></validatieObject>
				<!--
				<validatieObject><naam>LSkast</naam></validatieObject>
				<validatieObject><naam>LSkabel</naam></validatieObject>
				<validatieObject><naam>LSmof</naam></validatieObject>
				<validatieObject><naam>LSoverdrachtspunt</naam></validatieObject>
				<validatieObject><naam>OVLoverdrachtspunt</naam></validatieObject>
				<validatieObject><naam>HSstation</naam></validatieObject>
				<validatieObject><naam>HSkabel</naam></validatieObject>
				<validatieObject><naam>HSmof</naam></validatieObject>
				 -->
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.10" naam="Verplichte kenmerken moffen">
			<beschrijving>Iedere mof heeft kenmerken die gevuld moeten zijn.</beschrijving>
			<soort>Verplichte waarde</soort>
			<definitie>
				Iedere mof moet een waarde voor de volgende kenmerken hebben:
					- Functie
					- Verbindingnummer

				Aanvullend, iedere LSmof moet een waarde voor de volgende kenmerken hebben:
					- Bovengronds

				Aanvullend, iedere MSmof en HSmof moet een waarde voor de volgende kenmerken hebben:
					- NaamMonteur
					- CrossBondingAanwezig
			</definitie>
			<validatieObjecten>
				<validatieObject><naam>LSmof</naam></validatieObject>
				<validatieObject><naam>MSmof</naam></validatieObject>
				<validatieObject><naam>HSmof</naam></validatieObject>
			</validatieObjecten>
		</validatieRegel>
		<validatieRegel nummer="R.11" naam="Verplichte kenmerken LSoverdrachtspunt">
